version: "3"

services:
  bot:
    container_name: spp_base
    image: docker.marmon.info/master/jobs_for_sweetie_pie:latest
    restart: always
    ports:
      - 6080:8000

  rabbitmq:
    container_name: spp_rabbitmq
    image: rabbitmq:latest
    ports:
      - 5672:5672
    restart: always

  celery_worker:
    command: celery -A jobs_for_sweetie_pie worker -l info
    container_name: spp_celery-worker
    env_file:
      - .prod.full.env
    depends_on:
      - bot
      - db
      - rabbitmq
    image: docker.marmon.info/master/jobs_for_sweetie_pie:latest
    restart: always

  celery-beat:
    container_name: spp-celery-beat
    image: docker.marmon.info/master/jobs_for_sweetie_pie:latest
    command: celery -A jobs_for_sweetie_pie beat -l info
    env_file:
      - .prod.full.env
    depends_on:
      - rabbitmq